# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'AVIParser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'XCGLogger', '~> 6.0.4'

  # Pods for AVIParser

  target 'AVIParserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AVIParserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
